### ISSUE TITLE
Parameter 'zoom-to-fit' is unexpected

### ISSUE THREAD

**Issue by SteveDevOps** [wimpysworld/quickemu#1]
Hi Martin, I'm getting an error:

./quickemu.sh -vm ~/xtrabits/vm/qemu-vms/focal/focal.conf -virgil
focal.qcow2
focal.qcow2.snapshot
Formatting 'focal.qcow2', fmt=qcow2 size=68719476736 cluster_size=65536 lazy_refcounts=off refcount_bits=16
qemu-system-x86_64: -display gtk,grab-on-hover=on,zoom-to-fit=off: **Parameter 'zoom-to-fit' is unexpected**

my version:

 qemu-system-x86_64 --version
QEMU emulator version 4.0.0 (Debian 1:4.0+dfsg-0ubuntu9.4)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

**Comment by SteveDevOps** [comment]
ugh, looks like a bunch of new display options in 4.0 + it borked on edid option too after I tried leaving zoom off. Your advice appreciated: https://www.qemu.org/docs/master/system/invocation.html#hxtool-3

**Comment by izznogooood** [comment]
I get the same issue on 20.04.

Could it be the Ultra wide screen?
