### ISSUE TITLE
MX Linux not detecting the virtual HDD

### ISSUE THREAD

**Issue by AnErrupTion** [wimpysworld/quickemu#10]
After Windows 10 not detecting the virtual HDD, it's time for MX Linux (......)
![Capture du 2020-03-21 17-28-15](https://user-images.githubusercontent.com/49339966/77231151-69f42e00-6b99-11ea-8849-925e1a814ebe.png)
![Capture du 2020-03-21 17-28-36](https://user-images.githubusercontent.com/49339966/77231155-6e204b80-6b99-11ea-8e27-9deb1cb4d26c.png)

**Comment by flexiondotorg** [comment]
I can't reproduce this issue.

![Screenshot from 2020-03-21 17-19-00](https://user-images.githubusercontent.com/304639/77232348-67dd9f80-6b98-11ea-898a-4fbd1482ad35.png)

**Comment by AnErrupTion** [comment]
Nevermind, I fixed it, probably a problem from my fork.
