### ISSUE TITLE
disk_size conf param not honored

### ISSUE THREAD

**Issue by rpbpolis** [wimpysworld/quickemu#100]
When trying `quickemu --vm macos-big-sur.conf`, where the config file has a line disk_size="200G", it still becomes 64G when created.

**Comment by gregor160300** [comment]
Same here with windows 11

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/quickemu/commit/5ad176155ffebdb85bff53b6be77742ff9f9938b

Currently, the fix is in git only, not a released version.
