### ISSUE TITLE
Memory arithmetic error - integer expression expected

### ISSUE THREAD

**Issue by malgam** [wimpysworld/quickemu#11]
On my laptop running 20.04 with 8G memory, the "free -mega -h" command returns 7.9G total memory.  This causes a "integer expression expected" error for the following if statements and the $ram variable just defaults to "2G".

**Comment by AnErrupTion** [comment]
That's normal, you can't get to have 8G actual total memory. I have a VM which I've put 2G on but the system only detects 1.95G. What you can do is directly modify the default ram value to 4G for example.

**Comment by malgam** [comment]
I understand that it's possible to edit the script to manually set the VM memory allocation, but the reason I raised this was that the script throws errors on non-integer total memory sizes.  This can be avoided by changing the 'free' command to something like:
free --giga | grep Mem | tr -s ' ' | cut -d ' ' -f2
Maybe I'm just being a bit pedantic.
