### ISSUE TITLE
Windows 10 fails install - selected disk is of the GPT partition style

### ISSUE THREAD

**Issue by flattery103** [wimpysworld/quickemu#114]
Running on Manjaro, installing Windows 10 fails with the following error:
"Windows cannot be installed to this disk. The selected disk is of the GPT partition style."

**Comment by flexiondotorg** [comment]
Paste the Quickemu output please.

**Comment by flattery103** [comment]
[flattery@ManjaroOpti quickemu]$ ./quickemu -vm windows-10.conf 
Quickemu 2.2.5 starting windows-10.conf
 - QEMU:     /usr/bin/qemu-system-x86_64 v6.1.0
 - BOOT:     Legacy BIOS (windows) - EFI requested but no EFI firmware found.
 - CPU:      1 Socket(s), 2 Core(s), 1 Thread(s), 8G RAM
 - Disk:     windows-10/disk.qcow2 (64G)
             Just created, booting from windows-10/Win10_21H1_EnglishInternational_x64.iso
 - Boot ISO: windows-10/Win10_21H1_EnglishInternational_x64.iso
 - CD-ROM:   windows-10/virtio-win.iso
 - Display:  SDL, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-10" --port 5930 --spice-shared-dir /home/flattery/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Process:  On host:  killall windows-10       (if a forced kill is required)
[flattery@ManjaroOpti quickemu]$ qxl_send_events: spice-server bug: guest stopped, ignoring

**Comment by flattery103** [comment]
This fixed the problem "sudo pacman -Sy edk2-ovmf" Thanks
