### ISSUE TITLE
more-info: issues in running fedora 40

### ISSUE THREAD

**Issue by lucamosca1** [wimpysworld/quickemu#1245]
Environment: quickemu installed on Ubuntu 22.04

1 - Is it the correct iso?
iso downloaded is Fedora-Workstation-Live-osb-40-1.14.x86_64.iso, apart the osb variant, when running I see the pre-release alert in red like the beta version.

2 - Empty window on gnome
When running fedora, content of window are almost empty, making the installation process (and user setup) very difficult to complete, see attachment
![Schermata del 2024-05-22 15-07-52](https://github.com/quickemu-project/quickemu/assets/5502068/614c94a7-aa80-4a43-8d8d-2f779f2c77e6)

**Comment by flexiondotorg** [comment]
Please supply all the information requested via the issue template.

**Comment by lj3954** [comment]
I can replicate this. However, I believe this to be an issue with the media distributed by Fedora, not with quickemu. It does not impact the usability of the distribution in any way, you can install it normally using the anaconda installer linked to in the dash and everything should be fine post-install.
