### ISSUE TITLE
Unable to open VM if another VM is open with VirtualBox

### ISSUE THREAD

**Issue by rbharathkumar** [wimpysworld/quickemu#13]
Dear All,
My apologies for the several issues raised on the same day.
When I have a VM open inside VirtualBox, and if I try to use quickemu, I am getting the below error message.

```
ioctl(KVM_CREATE_VM) failed: 16 Device or resource busy
qemu-system-x86_64: failed to initialize KVM: Device or resource busy
```

Is it safe to assume that at a time, only either quickemu or virtualbox can be open ?

**Comment by flexiondotorg** [comment]
This is not a bug with QEMU or Quickemu. You can not have multiple hypervisors accessing VT-d at the same time.

**Comment by rbharathkumar** [comment]
Thank you for your response.
