### ISSUE TITLE
Mouse cursor not registering clicks at the location it looks like it should be after resizing QEMU window

### ISSUE THREAD

**Issue by mapitman** [wimpysworld/quickemu#147]
#### Expected behaviour

After resizing the QEMU window, when I click on a UI element in a guest OS, I expect that UI element to register the click.

#### Actual behaviour

When I click on a UI element, the click is registered at a different location in the guest OS's screen.

#### Steps to reproduce the behaviour

1. Use `quickget` to create a VM. I was able to reproduce this behavior with both Windows and Linux guests.
1. Start the vm using `quickemu --vm windows-11.conf`. This makes the VM use the SDL display.
1. Login to the guest OS if necessary.
1. Resize the QEMU window.
1. Click on any UI element. In order to see what's going on, I right-click on the desktop in the guest and I see a context menu popup in some other area besides where the cursor is displayed.

#### Quickemu output
```
quickemu --vm windows-11.conf 
Quickemu 2.2.6 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Ubuntu 21.10 running Linux 5.13 (colossus)
 - Guest:    Starting windows-11.conf as windows-11
 - CPU:      Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 1 Thread(s), 4G RAM
 - BOOT:     EFI (windows)
 - Disk:     windows-11/disk.qcow2 (64G)
 - CD-ROM:   windows-11/virtio-win.iso
 - TPM:      windows-11/windows-11.swtpm-sock (40162)
 - Display:  SDL, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-11" --port 5930 --spice-shared-dir /home/mark/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - smbd:     On guest: smb://10.0.2.4/qemu
```
#### Linux Distribution & Kernel
```
lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

uname -a
Linux colossus 5.13.0-20-generic #20-Ubuntu SMP Fri Oct 15 14:21:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I realize this may not be a quickemu specific problem, but I couldn't find anything that fixes the problem when I search for problems like this with QEMU. Also, since quickemu generates the command line parameters for QEMU, maybe there is something else it needs to add?

**Comment by Animeshz** [comment]
Any way to set this as default option when launched?
