### ISSUE TITLE
"qemu-system-x86_64: -audiodev: invalid option" Ubuntu 19.10

### ISSUE THREAD

**Issue by KaiLyons** [wimpysworld/quickemu#15]
This says it all, unsure what option is invalid but some option inside the section for -audiodev does not like.

**Comment by AnErrupTion** [comment]
Did you change the -audiodev option? If so, please give me the new line you've put.

**Comment by flexiondotorg** [comment]
@KaiLyons Please make sure you have current git of Quickemu and also the `qemu-virgil` snap installed. See the [README.md](https://github.com/wimpysworld/quickemu/blob/master/README.md) for updated install instructions.

**Comment by KaiLyons** [comment]
It was the newest, I installed qemu-virgil and did everything the README told me

**Comment by AnErrupTion** [comment]
My thought is that your qemu-virgil version is old.

**Comment by SneWs** [comment]
> It was the newest, I installed qemu-virgil and did everything the README told me

I recognize that error, I got that as well as I missed installing the --edge version of virgil. I had to uninstall virgil and then do a proper `snap install qemu-virgil --edge` to get that message to disappear.

**Comment by KaiLyons** [comment]
Yeah that was the issue, thanks!
