### ISSUE TITLE
Black screen on login using Xubuntu 19.10 and 20.04 daily builds

### ISSUE THREAD

**Issue by digitalight** [wimpysworld/quickemu#16]
Testing 20.04 daily builds of Xubuntu. The installation process completes as expected and the machine reboots to a login screen. But on logging into the system you are presented with a black screen and mouse cursor.
Have tested ubuntu, kubuntu and mate flavours and do not see this issue.
Have tested with Xubuntu 9.10 and get the black screen issue.
Running latest QuickEMU as of 26 March 2020 on Lenovo T530 with Intel Graphics 3rd Gen Core.

**Comment by AnErrupTion** [comment]
Did you try restarting the VM multiple times? I also had this problem with Xubntu 19.10 and after a couple of restarts the issue got fixed. I don't know why it happens though.

**Comment by digitalight** [comment]
Yes. That did not resolve the issue for me. I thought i had a workaround by changing the session from Xubuntu to XFCE it would boot but this only work for 1 boot, subsequent boots afterward left both XFCE and Xubuntu with black screen.

**Comment by AnErrupTion** [comment]
Is there a way you could try my fork to see if it works? If it doesn't, then that might be a QEMU issue then, or at least I think so.

**Comment by digitalight** [comment]
@AnErrupTion Your fork works for me. Will investigate further as to why Martin's doesn't work as your does. I notice they are both using virtio-vga but you have extra stuff in yours. Will check out differences.
Thanks for pointing me in a direction :)

**Comment by AnErrupTion** [comment]
No problem ;)

**Comment by digitalight** [comment]
Have found the issue in Wimpy's script.
By changing `local VIRGL="on"` to `local VIRGL="off"`
Xubuntu is now usable.
Not sure what other feature will be disabled because of this but it is a fix in my case. :)

**Comment by AnErrupTion** [comment]
That is then, an issue with qemu-virgil. We can't do anything about that, except changing the default value and, perhaps, in the configuration file.
