### ISSUE TITLE
Segmentation fault when conf has no newline at end of file

### ISSUE THREAD

**Issue by CarwynNelson** [wimpysworld/quickemu#17]
## Description

When investigating another issue where I was unable to install ubuntu 19.10 I tried to install ubuntu-mate 19.10 for comparison to see if my issue was specific to ubuntu "proper".

Towards the end of the installation `quickemu` crashed due to a segmentation fault with the following output:

```
./quickemu: line 136: 26666 Segmentation fault      (core dumped) ${QEMU} -name ${VMNAME},process=${VMNAME} -enable-kvm -machine q35 ${GUEST_TWEAKS} ${CPU} -smp ${CORES_VM} -m ${RAM_VM} -device virtio-balloon -drive if=pflash,format=raw,readonly,file="${EFI_CODE}" -drive if=pflash,format=raw,file="${EFI_VARS}" -drive media=cdrom,index=0,file="${iso}" -drive media=cdrom,index=1,file="${driver_iso}" -drive if=none,id=drive0,cache=directsync,aio=native,format=qcow2,file="${disk_img}" -device virtio-blk-pci,drive=drive0,scsi=off ${STATUS_QUO} ${VIDEO} -display ${OUTPUT},gl=${GL}${OUTPUT_EXTRA} -device qemu-xhci,id=xhci,p2=8,p3=8 -device usb-kbd,bus=xhci.0 -device usb-tablet,bus=xhci.0 ${USB_PASSTHROUGH} -device virtio-net,netdev=nic -netdev ${NET},id=nic -audiodev pa,id=pa,server=unix:${XDG_RUNTIME_DIR}/pulse/native,out.stream-name=${LAUNCHER}-${VMNAME},in.stream-name=${LAUNCHER}-${VMNAME} -device intel-hda -device hda-duplex,audiodev=pa,mixer=off -rtc base=localtime,clock=host -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 -spice port=5930,disable-ticketing -device virtio-serial-pci -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 -chardev spicevmc,id=spicechannel0,name=vdagent -serial mon:stdio "${@}"
```

After some debugging I have noticed that the crash only happens when my `.conf` file lacks a newline at the end of the file.

When looking at the revisions tab of this gist https://gist.github.com/CarwynNelson/bac12dbb12e220ba7dd7cce2db40ed9a/revisions you can see the subtle difference.

## Additional Details

When I first launch quickemu I get the following output:
```
Starting ../qemu/ubuntu-mate-19.10.conf
 - QEMU:     /snap/bin/qemu-virgil v4.2.0
 - BOOT:     EFI
 - Guest:    Linux optimised
 - Disk:     /home/carwyn/Development/qemu/ubuntu-mate-19.10.qcow2 (128G)
             Just created, booting from /home/carwyn/Development/qemu/ubuntu-mate-19.10.iso
 - Boot:     /home/carwyn/Development/qemu/ubuntu-mate-19.10.iso
 - CPU:      4 Core(s)
 - RAM:      2G
 - Screen:   1664x936
 - Video:    virtio-vga
 - GL:       ON
 - Virgil3D: ON
 - Display:  SDL
 - smbd:     /home/carwyn will be exported to the guest via smb://10.0.2.4/qemu
 - ssh:      22228/tcp is connected. Login via 'ssh user@localhost -p 22228'

BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00001 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00001 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0)
gl_version 45 - core profile enabled
GLSL feature level 430
```

I was doing a minimal install of ubuntu-mate 19.10 (latest torrent download) with updates installing as part of the install, but **no third party drivers selected.**

Here is a snippet of information from `neofetch` for my system specifications:
```
OS: Ubuntu 19.10 x86_64 
Host: ROG Strix G531GW_G531GW 1.0 
Kernel: 5.3.0-42-generic 
Shell: zsh 5.7.1 
Resolution: 1920x1080 
DE: GNOME 3.34.3 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: tilix 
CPU: Intel i7-9750H (12) @ 4.500GHz 
GPU: NVIDIA GeForce RTX 2070 Mobile 
GPU: Intel UHD Graphics 630 
Memory: 4164MiB / 15861MiB 
```

**Comment by AnErrupTion** [comment]
Go at line 460 in quickemu, and change `source "${VM}"` to `. "${VM}"`. It's another way to read configuration files, so you might try it and see if it's a problem related to the `source` command.

**Comment by CarwynNelson** [comment]
Strangely I am no longer able to replicate this bug, even though yesterday I was able to do so quite consistently.

I am not sure whether to leave this open to see if others can replicate the issue, or to close it and treat it as a weird blip in the spacetime continuum.

PS: I tried your fix, but as I was not able to replicate the crash at all without it I'm not sure if it worked or not.

**Comment by AnErrupTion** [comment]
Well, you should leave it open for now as it's a very weird glitch, probably from the `source` command or just a random problem. We'll see anyway!

**Comment by flexiondotorg** [comment]
I can't reproduce this issue. If you are able to find a way to reproduce it reliably then please let me know.
