### ISSUE TITLE
Catalina doesn't start

### ISSUE THREAD

**Issue by alexander-potemkin** [wimpysworld/quickemu#177]
#### Expected behaviour

```
quickget macos catalina
quickemu --vm macos-catalina.conf
```

to install Catalina.

#### Actual behaviour

Guess some installation happened - I've got black screen saying something like the system will shutdown now; I closed the window, restarted with `quickemu --vm macos-catalina.conf` and got error attached.

#### Steps to reproduce the behaviour

```
quickget macos catalina
quickemu --vm macos-catalina.conf
```

#### Quickemu output

```
$ quickemu --vm macos-catalina.conf
Quickemu 2.2.7 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Linux Mint 20.2 running Linux 5.4 (x280linux)
 - CPU:      Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 4G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-catalina/disk.qcow2 (96G)
             Just created, booting from macos-catalina/RecoveryImage.img
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - Recovery: macos-catalina/RecoveryImage.img
 - Display:  SDL, qxl, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "macos-catalina" --port 5930
 - 9P:       On guest: sudo mount_9p Public-alex
 - 9P:       On host:  chmod 777 /home/alex/Public
             Required for macOS integration 👆
 - Process:  Starting macos-catalina.conf as macos-catalina (282188)

$ qemu-system-x86_64: Slirp: Failed to send packet, ret: -1
qemu-system-x86_64: Slirp: Failed to send packet, ret: -1

$ quickemu --vm macos-catalina.conf
Quickemu 2.2.7 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Linux Mint 20.2 running Linux 5.4 (x280linux)
 - CPU:      Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 4G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-catalina/disk.qcow2 (96G)
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - Display:  SDL, qxl, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "macos-catalina" --port 5930
 - 9P:       On guest: sudo mount_9p Public-alex
 - 9P:       On host:  chmod 777 /home/alex/Public
             Required for macOS integration 👆
 - Process:  Starting macos-catalina.conf as macos-catalina (285995)

```

#### Linux Distribution & Kernel

Run the following and paste the output.

```$ lsb_release --all
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename:	uma

$ uname -a
Linux x280linux 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```
![Screenshot from 2021-10-29 19-27-23](https://user-images.githubusercontent.com/2323840/139470635-a6345f09-2e11-4cb9-b6b2-e030938a7b9d.png)

**Comment by flexiondotorg** [comment]
I don't think you have completed the installation. Delete the VM disk and run the install, all the way through:

```bash
quickemu --vm macos-catalina.conf --delete
```

**Comment by ymauray** [comment]
Maybe the installer went in sleep mode. It happened to me once. Now, I always have an eye on the VM while it installs, making sure to keep it awake by moving the mouse over it.
Can you try that ? If that's confirmed, we should update the README.

**Comment by alexander-potemkin** [comment]
> Maybe the installer went in sleep mode. It happened to me once. Now, I always have an eye on the VM while it installs, making sure to keep it awake by moving the mouse over it.
> Can you try that ? If that's confirmed, we should update the README.

That's very much possible, thank you. Because I've seen it was installing and then it was just a blank screen - unfortunately I didn't screenshot it, as I thought that it's a normal end of the installation procedure and I need to restart.

Let me retry keeping up an eye on the installation and screenshotting the black screen if it will appear.

**Comment by alexander-potemkin** [comment]
![catalina-fail](https://user-images.githubusercontent.com/2323840/139865541-b5471237-f98b-4a12-bc64-8c88c2ce11f4.png)
Seems like something went wrong during the installation... any help would be much appreciated!

**Comment by flexiondotorg** [comment]
Looks like you are having difficulty installing macOS, rather than a bug in Quickemu. Please come are discuss this in our Discord.

  * https://wimpysworld.io/discord
