### ISSUE TITLE
Support Windows LTSC

### ISSUE THREAD

**Issue by mvdan** [wimpysworld/quickemu#179]
See https://techcommunity.microsoft.com/t5/windows-it-pro-blog/ltsc-what-is-it-and-when-should-it-be-used/ba-p/293181.

The summary is that the LTSC edition of Windows gets updated less often, and contains fewer components than a regular Windows install - generally meaning a faster install and lower resource usage (disk, CPU, etc).

For instance, you can obtain an install image for LTSC here: https://www.microsoft.com/en-gb/evalcenter/evaluate-windows-10-enterprise

Does quickemu support downloading a Windows edition like LTSC?

**Comment by flexiondotorg** [comment]
Anyone wanting to run Windows LTSC can do by downloading the ISO manually and creating a suitable Windows VM configuration 🙂

The LTSP can't be automated, as far as I am aware, so I won't be adding it Quickemu. If I'm wrong about that 👈 then pull requests are welcome!

**Comment by mvdan** [comment]
Could you clarify what you mean by automated? I just installed Windows 10 using quickemu, and the installation process still included some manual steps.

As far as I know, the LTSC version is a regular old install ISO, so it should work the same as regular install ISOs. I can give it a try later if that sounds useful in terms of verifying.

**Comment by tekumara** [comment]
+1 LTSC is supported by https://github.com/dockur/windows would be awesome to support here!
