### ISSUE TITLE
Android X86 support

### ISSUE THREAD

**Issue by matteoturini** [wimpysworld/quickemu#180]

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/quickemu/pull/174

**Comment by matteoturini** [comment]
@flexiondotorg Didn't add 9.0-r2, also forgot to mention BlissOS, a really popular Android x86 based OS. Also, the generated .conf file is incomplete, missing OS name and faulty iso declaration.

**Comment by daPhipz** [comment]
I (and other contributors to the project, I am sure) think it would be cool if you could word your request a little nicer.
I am sure that you don't mean any harm or want to bully someone, but I think that more people are willing to implement the thing, if the request is worded friendly. Thank you! ❤️

**Comment by matteoturini** [comment]
Oops, so sorry. I was pretty tired yesterday and I apologize.

Em dom., 31 de out. de 2021 16:13, Philipp Kiemle ***@***.***>
escreveu:

**Comment by daPhipz** [comment]
No worries ☺️
