### ISSUE TITLE
Incorrect report of insufficient memory

### ISSUE THREAD

**Issue by mattmole** [wimpysworld/quickemu#181]
#### Expected behaviour

VM should run (I've tried mac os catalina and Win 11)

#### Actual behaviour

The VM will not run, whether trying macos or Windows

#### Steps to reproduce the behaviour

Following the usage of quickget and quickemu, I see the error detailed below. This occurs whether using mac os catalina or Windows 11. I've not tried others

#### Quickemu output

Quickemu 2.3.1 using /usr/bin/qemu-system-x86_64 v6.1.0
 - Host:     "Fedora release 35 (Thirty Five)" running Linux 5.14 (fedora)
 - CPU:      Intel(R) Celeron(R) CPU N3350 @ 1.10GHz
 - CPU VM:   1 Socket(s), 1 Core(s), 1 Thread(s), 2G RAM
ERROR! You have insufficient RAM to run windows in a VM

#### Linux Distribution & Kernel

LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 35 (Thirty Five)
Release:        35
Codename:       ThirtyFive

Linux fedora 5.14.10-300.fc35.x86_64 #1 SMP Thu Oct 7 20:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/10687725/139499362-af1dbc7d-4c02-4471-80cd-1e6ad85051d0.png)

I realise the laptop I'm using is a stupidly low spec device, but I have been able to run VMs on it in the past (just slowly)

Thanks

**Comment by flexiondotorg** [comment]
This report is correct. Quickemu automatically allocates RAM to the VM based on how much RAM the host has. 2GB is insufficient for Windows. 

You can override the RAM allocation manually:

  * https://github.com/wimpysworld/quickemu#tuning-cpu-cores-ram--disks

**Comment by mattmole** [comment]
Thanks Wimpy. So, is the error essentially saying "I've allocated 2GB from your 6GB total and this isn't enough for the VM"? I'd read it slightly differently, in that it had allocated 2GB to the VM (which did seem a bit low) and tried to run it and that it didn't think 2GB was available at run time when it was. As the 2GB was available I got a bit confused

**Comment by daPhipz** [comment]
> I'd read it slightly differently, in that it had allocated 2GB to the VM

This is exactly the case. Quickemu looks at the total RAM of the host (in your case 6GB), and then allocates a portion of that to the VM. If you have more RAM in total, the VM gets more, if you have less, the VM gets less. This ensures that you can still operate your host OS reasonably well, and that the VM doesn't take all RAM that's available ;)

As Wimpy said, you can override this behaviour and allocate as much RAM as you want by following the instructions in the README.

**Comment by mattmole** [comment]
Thanks!
