### ISSUE TITLE
Use distro-specific icons from Lukewh/quickemu-icons for shortcuts

### ISSUE THREAD

**Issue by daPhipz** [wimpysworld/quickemu#183]
@Lukewh provides distro-specific icons for `quickemu` in their repo. I think it would be nice if we would use them for shortcuts created by `quickemu --shortcut`, instead of just the quickemu icon.

**Comment by Lukewh** [comment]
If this is going to happen, I think there are at least three options:
1. `quickemu` pulls down the latest release and extracts the appropriate icon (a lot of effort for `quickemu` with extra downloads etc. that seem out of scope for `quickemu`)
2. the `quickemu-icons` repo exposes the icons at consistent URLs that `quickemu` can download on demand when the `--shortcut` argument is passed
3. `quickemu` includes all the latest icons in its release
