### ISSUE TITLE
Tipo in Readme

### ISSUE THREAD

**Issue by navycatt** [wimpysworld/quickemu#186]
https://github.com/wimpysworld/quickemu/blob/7ac2768784d68a4542c4767265265c4e5d56280d/README.md?plain=1#L491
Do you mean `quickemu` not `quickget`.

**Comment by matteoturini** [comment]
No, quickget generates the config.

**Comment by navycatt** [comment]
Yeah. I got the joke. For windows 11, quickget adds this line to the config.
