### ISSUE TITLE
macos - fetch-macos.py - ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by digitalight** [wimpysworld/quickemu#20]
Following instructions for macos.
After chmod +x fetch-macos.py
when I run fetch-macos.py I get the following error.
Running this on Manjaro 19.0.2

Understand that this part is not your script so will be file issue with github project that this comes from. But adding issue here as it affects your project also.

> ./fetch-macos.py
> Traceback (most recent call last):
>   File "./fetch-macos.py", line 9, in <module>
>     import click
> ModuleNotFoundError: No module named 'click'

**Comment by digitalight** [comment]
Found similar issue:
https://github.com/foxlet/macOS-Simple-KVM/issues/17

I fixed my issue by (on Manjaro):
sudo pacman -S python-click

For some reason the script does not download the module automatically.

**Comment by SneWs** [comment]
Aldo I'm not a Python guy, I think a more correct way of resolving this would be to do a `pip3 install click`

**Comment by wmutschl** [comment]
I also had to change the very first line of the scrict `fetch-macos.py` to `#!/usr/bin/python3`.

**Comment by danielw2904** [comment]
Just to reiterate @wmutschl's point: the `fetch-macos.py` script requires python3 so if `/usr/bin/python` links to version 2.x you'll get this error. Either change the first line or specifically call `python3 fetch-macos.py` (at least on ubuntu)
