### ISSUE TITLE
AVX2 is actually not required to run macOS

### ISSUE THREAD

**Issue by lfom** [wimpysworld/quickemu#201]
#### Expected behaviour

`quickemu` fails to run a macOS VM when AVX2 is not supported by the host CPU.

#### Actual behaviour

`quickemu` should run the macOS VM even if AVX2 is not supported by the host CPU.

#### Steps to reproduce the behaviour

1. Create a macOS configuration on a machine with a processor without AVX2 support
2. Run `quickemu -vm macos.conf`
3. quickemu stops with the error below:
ERROR! macOS requires a CPU with SSE 4.1 and AVX2 support.

#### Quickemu output

```
$ quickemu --screen 0 --vm macos.conf
Quickemu 2.3.0 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Pop!_OS 21.04 running Linux 5.13 (imac-pop)
 - CPU:      Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 1 Thread(s), 4G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
ERROR! macOS requires a CPU with SSE 4.1 and AVX2 support.
```

#### Linux Distribution & Kernel

```bash
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute

Linux imac-pop 5.13.0-7620-generic #20~1634827117~21.04~874b071-Ubuntu SMP Fri Oct 29 15:06:55 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

The only reference that running macOS requires AVX2 was from [OSX-KVM repo](https://github.com/kholia/OSX-KVM), but if you look at their code, it does not use it (only AVX is listed):
https://github.com/kholia/OSX-KVM/blob/97277bc056916bf6621400a91b8a3d367d59ec9b/OpenCore-Boot.sh#L16

I have an iMac Mid-2011 that is running Pop!_OS now (as shown above), and it is possible to install Mojave, Catalina and even BigSur natively, but the CPU is an Intel i5-2500S with no AVX2 (it is not usable as daily driver because the stock GPU does not support Metal tho). Even much older CPUs, up to [Penryn can run Catalina](http://dosdude1.com/catalina/), and I am able to run them here using `qemu` as well.

My guess is that only SSE4.1 is a requirement to run macOS (applications/games may require AVX2, but they will simply tell you that when started, no crashes or whatever) and perhaps AVX2 is required for Monterey and up only?

**Comment by jpmorrison** [comment]
Catalina runs without avx2  just change quickemu to check_cpu_flag avx 

-cpu can be set to host or kvm64 as well, doesn't need to be Penryn

**Comment by tunerooster** [comment]
> Catalina runs without avx2 just change quickemu to check_cpu_flag avx
> 
> -cpu can be set to host or kvm64 as well, doesn't need to be Penryn

I cannot find how to do this.  I am trying to run macos on a Intel Core 2 Duo.  Where/how do I do what you suggest above?  Or am I wasting my time...?  I.e., it won't ever work...  (I have tried all available macos versions).

Thanks!

**Comment by lfom** [comment]
> I am trying to run macos on a Intel Core 2 Duo.

I am afraid it works only if it is a Penryn-base CPU, like the T9300.

**Comment by tunerooster** [comment]
OK, thanks for your reply!
