### ISSUE TITLE
Add Windows 11 HW req bypass flag

### ISSUE THREAD

**Issue by domingo13** [wimpysworld/quickemu#210]
I have been struggling with getting Windows 11 to work with the well know hardware requirement issue.

The annoying thing is that it used to work and then suddenly stopped working.

I dug into the autounattend.xml and found a snippet on the internet which bypasses the hardware check during the install:
 `
 <RunSynchronous>
                <RunSynchronousCommand wcm:action="add">
                    <Order>1</Order>
                    <Path>reg add HKLM\System\Setup\LabConfig /v BypassTPMCheck /t reg_dword /d 0x00000001 /f</Path>
                </RunSynchronousCommand>
                <RunSynchronousCommand wcm:action="add">
                    <Order>2</Order>
                    <Path>reg add HKLM\System\Setup\LabConfig /v BypassSecureBootCheck /t reg_dword /d 0x00000001 /f</Path>
                </RunSynchronousCommand>
                <RunSynchronousCommand wcm:action="add">
                    <Order>3</Order>
                    <Path>reg add HKLM\System\Setup\LabConfig /v BypassRAMCheck /t reg_dword /d 0x00000001 /f</Path>
                </RunSynchronousCommand>
                <RunSynchronousCommand wcm:action="add">
                    <Order>5</Order>
                    <Path>reg add HKLM\System\Setup\LabConfig /v BypassCPUCheck /t reg_dword /d 0x00000001 /f</Path>
                </RunSynchronousCommand>
                <RunSynchronousCommand wcm:action="add">
                    <Order>4</Order>
                    <Path>reg add HKLM\System\Setup\LabConfig /v BypassStorageCheck /t reg_dword /d 0x00000001 /f</Path>
                </RunSynchronousCommand>
            </RunSynchronous>
`

With these lines inserted into quickget where it builds the xml file I was able to get a Windows 11 installing with out any fuss.

I know this isn't the right way around it but when the installer suddenly moves the bar and don't tell you why it thinks your machine isn't good enough then this could save a lot of time.

**Comment by diddledani** [comment]
I'd rather not include hacking the Windows install because it isn't going to give users who aren't supported a good experience if MS drops them in the mud. Also there's no guarantee that supported users installations aren't going to get killed at the same time if that happens

**Comment by flexiondotorg** [comment]
I agree with @diddledani assessment. Thanks for contributing though 🙂
