### ISSUE TITLE
Fall back to wget if zsync not available

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/quickemu#212]
@flexiondotorg mentioned on the stream a comment from @cowboygeneral that not every distro (Fedora 35) has zsync in the repo, and that we need to take care of that both in the gui and in quickget.

Suggestion: if zsync not found in path then set a guard that prevents zsync-only options from showing, listing or getting

Hopefully masking them out of the output of list then quickgui will just work.

**Comment by daPhipz** [comment]
All right, I'll be updating the KDE Neon stuff then - currently, the only way we download these ISOs is via `zsync`.

**Comment by philclifford** [comment]
Yes, if we add logic to fall back to wget if no zsync and add some text to the README ...

**Comment by daPhipz** [comment]
> in the function call would be ideal

Very good idea! If I am not mistaken, we could (in the `zsync_get` function) simply drop the `.zsync` bit of the URL and pass it on to the `web_get` function. That would work, wouldn't it?
