### ISSUE TITLE
Broken network after bridge support in PR #160

### ISSUE THREAD

**Issue by navycatt** [wimpysworld/quickemu#215]
#### Expected behaviour

![Снимок экрана в 2021-11-09 13-23-52](https://user-images.githubusercontent.com/92228311/140907225-aab36ea3-1c97-426a-8e42-5133997b5fea.png)

#### Actual behaviour

![Снимок экрана в 2021-11-09 13-21-43](https://user-images.githubusercontent.com/92228311/140907319-9710fba2-5898-4937-813f-c74cdc74982f.png)

#### Steps to reproduce the behaviour

This happens when you have installed a virtual machine with quickemu 2.2.7 and below and then upgraded quickemu to 2.2.8 and above. PR https://github.com/wimpysworld/quickemu/pull/160 breaks the network.

1. Install quickemu 2.2.7 and below.
2. Install the virtual system from the image.
3. Upgrade quickemu to 2.2.8 or higher (you can use the latest or master).
4. Start the installed system from point 2.

It looks like qemu forms the name of the network device by the sequence number of the device in the parameters.
Prior to quickemu 2.2.8, the device sequence number was 4 and the device name was enp0s4.
Since quickemu 2.2.8, the device sequence number is 7 and the device name is enp0s7.
Therefore, after the quickemu update, the virtual machine cannot automatically bring up the network, since the device name has changed.

To fix this we need to reconfigure the network. In my case, I need to reconfigure the netplan config.

#### Quickemu output

Quickemu 2.3.1 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Ubuntu 21.10 running Linux 5.13 (ultra-sparc)
 - CPU:      Intel(R) Core(TM) i7-4960X CPU @ 3.60GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 4G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/OVMF/OVMF_CODE_4M.fd), SecureBoot (off).
 - Disk:     ubuntu-server/disk.qcow2 (16G)
 - Display:  GTK, virtio-vga, GL (off), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - PORTS:    Port forwards requested:
              - 80 => 80
              - 2222 => 22
              - 3306 => 3306
 - SPICE:    On host:  spicy --title "ubuntu-server" --port 5930 --spice-shared-dir /home/navycat/Общедоступные
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-navycat ~/Общедоступные
 - Process:  Starting ubuntu-server.conf as ubuntu-server (20896)

#### Linux Distribution & Kernel

Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
Linux ultra-sparc 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by navycatt** [comment]
Fix here https://github.com/wimpysworld/quickemu/pull/217

**Comment by philclifford** [comment]
This is in no way broken for me: just made another couple of VMs to test and the network is fine.  Maybe your networking locally is "special" or unusual

**Comment by navycatt** [comment]
Updated Steps to reproduce behavior.

**Comment by navycatt** [comment]
Updated Steps to reproduce behavior.

**Comment by navycatt** [comment]
> This is in no way broken for me: just made another couple of VMs to test and the network is fine. Maybe your networking locally is "special" or unusual

This happens when you have installed a virtual machine with quickemu 2.2.7 and below and then upgraded quickemu to 2.2.8 and above.

**Comment by navycatt** [comment]
> This is in no way broken for me: just made another couple of VMs to test and the network is fine. Maybe your networking locally is "special" or unusual

This happens when you have installed a virtual machine with quickemu 2.2.7 and below and then upgraded quickemu to 2.2.8 and above.

**Comment by philclifford** [comment]
I just spent a few hours testing old (pre-2.2.7 installed) VMs and checking out 2.2.7, building ubuntu-mate and ubuntu-studio with that version, then pulling 2.2.9 and current.  In all cases no networking issues: same device name comes up every time working. So looking like this may be specific to ubuntu server.  Will try that later.

**Comment by philclifford** [comment]
Or not : 
```
home/phil/quickemu$quickemu --version
2.2.7
/home/phil/quickemu$quickget ubuntu
ERROR! You must specify a release: bionic focal hirsute impish devel canary
/home/phil/quickemu$quickget 
ERROR! You must specify an operating system:
elementary freebsd fedora kali kubuntu linuxmint-cinnamon linuxmint-mate linuxmint-xfce nixos-gnome nixos-plasma5 nixos-minimal lubuntu macos openbsd opensuse popos ubuntu ubuntu-budgie ubuntu-kylin ubuntu-mate ubuntu-studio windows xubuntu

---

/home/phil/quickemu$quickget --version
Quickemu Version: 2.3.1
/home/phil/quickemu$quickget ubuntu
ERROR! You must specify a release: bionic focal hirsute impish devel canary
/home/phil/quickemu$quickget 
ERROR! You must specify an operating system:
android archlinux elementary freebsd fedora garuda kali kdeneon kubuntu linuxmint-cinnamon linuxmint-mate linuxmint-xfce nixos-gnome nixos-plasma5 nixos-minimal lubuntu macos openbsd opensuse popos regolith rockylinux solus ubuntu ubuntu-budgie ubuntu-kylin ubuntu-mate ubuntu-studio windows xubuntu zorin

```
so `ubuntu-server` came about how ?

It's about this point that maybe the right solution is either fix the network by hand has you have, or
 `quickemu --vm <broken vm>.conf --delete`, maybe ` rm <broken vm>/<broken vm>.sh` and then just run up a fresh one using the latest version.

**Comment by navycatt** [comment]
Ubuntu Mate is not affected by this because it uses NetworkManager as a renderer and does not use the device name. 
It looks like the problem only occurs in Ubuntu Server. Since ubuntu server is not officially supported by quickemu, I close the issue.
