### ISSUE TITLE
Android not working in quickemu/quickgui

### ISSUE THREAD

**Issue by ardsur** [wimpysworld/quickemu#219]
#### Expected behaviour

expect android to start on quickemu -vm android-9.0.conf
expect android to start when clicking > in quickgui

#### Actual behaviour

quickemu gives error message 
"WARNING! Unrecognised guest OS:
-Disk: android-9.0/disk.qcow2 (32G)
Looks unused, booting from
ERROR!   You haven't specified a .iso or .img image to boot from. "

quickgui, just does nothing, no error message 

#### Steps to reproduce the behaviour

on 2nd try it showed same behavior

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```
##################################################################################
**Fault finding**

the .conf file did not show the guest system but guest_os="" ; I corrected this with guest_os="linux"
the line for the iso started with =   ; I corrected this with putting iso in front 
(this after checking the .conf file for Ubuntu-devel.conf)

after saving the android system was working correct and opened normally both with quickemu and quickgui

thanks for this fantastic tool to run a VM

**Comment by philclifford** [comment]
Thanks @ardsur  - this should now be fixed if PR #221 is merged

**Comment by ardsur** [comment]
thanks a lot for repairing my fault finding. 
it is my very first contribution to any Github project, :) 
now , I will start reading how Github works and figure out whether I could use this myself.
