### ISSUE TITLE
Add parameter -global ICH9-LPC.disable_s3=1 for arch linux to boot secureboot=on

### ISSUE THREAD

**Issue by l-t-k** [wimpysworld/quickemu#220]
My windows 11 virtual machine wasn't able to boot with secureboot=on until I added -global ICH9-LPC.disable_s3=1 to line 503:
https://github.com/wimpysworld/quickemu/blob/d3506d1c4a318156213b5b18fdbc46c048aa26e8/quickemu#L503

For more info, see:
https://wiki.archlinux.org/title/QEMU#VM_does_not_boot_when_using_a_Secure_Boot_enabled_OVMF

Not sure how other distro's are affected if you add this parameter globally to the script

**Comment by philclifford** [comment]
It was only recently removed to close #162. Could you confirm (or correct) my presumption that you're on Arch.  If you could please at least provide the output of `quickemu --vm windows-11.conf` we'll have more to go on. Thanks.
