### ISSUE TITLE
macos - boot loop

### ISSUE THREAD

**Issue by digitalight** [wimpysworld/quickemu#23]
Can not install macos using QuickEMU.
Following instructions in the guide.
When I run:
./quickemu --vm macos.conf
I see the os boot but quickly reboots itself.
Have recorded the screen and uploaded here:
https://youtu.be/bCLZB1T8vRA

**Comment by digitalight** [comment]
My config file is as follows:
```
guest_os="macos"
img="macos/BaseSystem.img"
disk_img="macos/macos.qcow2"
disk=128G
```

**Comment by SneWs** [comment]
I'll second this, seeing the boot loop as well for macos. 
From the boot of macos I can see that we have
1) Problem detecting swap
2) DMA errors on disk24

But not sure if that is anything related to this issue or not as I'm not well versed in macos boot/io stuff.

**Comment by SneWs** [comment]
Figured out what was going wrong... Martin has used rot13 to "cypher" the "secret" osx key needed. So installing hxtools will give you rot13 support. This solved it for me at least. 

`sudo apt-get install hxtools`
Verify with being able to issue `rot13`. Once that works you should be able to boot osx installer.

**Comment by digitalight** [comment]
Thanks @SneWs.
I watched @flexiondotorg stream as well and totally forgot about his very advanced encrypting.
It stopped me so I guess it did it's job :rofl: 
@flexiondotorg Could this be added in the documentation if hxtools is not installed by default.
For Arch users finding this I had to go to the AUR. `yay -S hxtools`
Installing the OS now so finders crossed all good now...

**Comment by SneWs** [comment]
> For Arch users finding this I had to go to the AUR. `yay -S hxtools`
Perhaps a more light weight solution on Arch would be to use https://aur.archlinux.org/packages/rot13/ ?

**Comment by demian-mint** [comment]
You need to add the line cpu_cores="1" to the config file.
