### ISSUE TITLE
KVM/virsh integration

### ISSUE THREAD

**Issue by mhalano** [wimpysworld/quickemu#234]
#### Expected behaviour

Would be nice to have the VMs created by Quickemu be showed with virsh and available to use over virt-manager

#### Actual behaviour

The VMs don't show in virsh or virt-manager.

#### Steps to reproduce the behaviour

Create a VM with Quickemu. Add a connection to QEMU/KVM session (not system) and try to see all the VMs.

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
Linux glados.lan 5.15.2-051502-generic #202111121041 SMP Fri Nov 12 16:26:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by flexiondotorg** [comment]
Sorry, this is out of scope for the project 😞
