### ISSUE TITLE
pulse error spamming terminal 

### ISSUE THREAD

**Issue by popey** [wimpysworld/quickemu#25]
In my VMs, once they launch, I get this spamming the terminal:

```
pulseaudio: pa_threaded_mainloop_lock failed
pulseaudio: Reason: Access denied
```
This makes the terminal messy, and means the nice quickemu launch information dump is thrown off screen.

**Comment by monetaryabyss** [comment]
I was able to get it to quiet down with a `snap connect qemu-virgil:audio-record`. I am not certain that is the proper fix but it did suppress the noise.

**Comment by popey** [comment]
Bingo! That got it, thanks @monetaryabyss
