### ISSUE TITLE
Windows10 example sees no disk to install to

### ISSUE THREAD

**Issue by kbknapp** [wimpysworld/quickemu#27]
Following the example from the README, everything works (minus #26 ) until I get to the portion of the windows install to select Upgrade/Custom...

Picking Upgrade fails because no install exists.

Picking Custom shows now drives, and will not allow one to continue until a drive can be found.

**Comment by kbknapp** [comment]
I forgot, my details

Ubuntu: 19.10 (Regolith)
Quickemu version: HEAD 64cff9bba
qemu-virgil version: 
```
qemu-virgil --version
QEMU emulator version 4.2.0 (v4.2.0-dirty)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
```

**Comment by digitalight** [comment]
Can you confirm that you did the following setups in order to see a drive:

> During the Windows 10 install you will be asked "Where do you want to install Windows?"
> Click Load driver and OK the the dialogue box that pops up.
> Select VirtIO SCSI controller (E:\amd64\w10\viostor.inf) from the list and click Next.
> The disk will now be available for partitioning and formatting.

**Comment by kbknapp** [comment]
Well that's embarrassing! Apologies! This can be closed.

**Comment by meherhendi** [comment]
Here's what worked for me:

1- Downloaded the stable virtio driver from here [virtio](https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/README.md) 
2- Ran with `--display spice` like this `quickemu --vm windows-10.conf --display spice` 
3- Mounted the virtio iso from ** Toolbar - Input - Select USB devices for redirection - spicecd ** then select virtio ISO

Voila! The device drivers appear after hitting refresh, and you'll be able to select disks to install Windows
