### ISSUE TITLE
Could not create file: No such file or directory- Cant create VM Disk File

### ISSUE THREAD

**Issue by osgyan** [wimpysworld/quickemu#31]
Can't create qcow2 file on a second internal disk mounted at /Data. Permissions on the folder are correct, 0777, so everyone can create files. The disk formatted with xfs file system. I can use virt-manager to create VMs Just fine. I am not sure if there is support for xfs in the script, or the virgil KVM Snap is able to talk to the disk. 
My general observation has been that Snaps are blind to anything outside of the primary Operating System disk.
My config file.
__________________________________
boot="efi"
guest_os="linux"
iso="/Data/KVM/Isos/ubuntu-20.04-beta-desktop-amd64.iso"
disk_img="/Data/KVM/Disks/focal-desktop-amd64.qcow2"
disk=128G
____________________________________
Error Message
__________________________________
rajat@beasty:~/quickemu/quickemu$ ./quickemu --vm ubuntu.conf 
Starting ubuntu.conf
 - QEMU:     /snap/bin/qemu-virgil v4.2.0
 - BOOT:     EFI
 - Guest:    Linux optimised
 - Disk:     /Data/KVM/Disks/focal-desktop-amd64.qcow2 (128G)
qemu-img: /Data/KVM/Disks/focal-desktop-amd64.qcow2: Could not create file: No such file or directory
ERROR! Failed to create /Data/KVM/Disks/focal-desktop-amd64.qcow2
_____________________________________________________

**Comment by digitalight** [comment]
Hi osgyan,
I had this issue a while back. It's because snaps that are contained and not run under --classic can not see the /data path.
You need to do either:

1. run ``snap connect qemu-virgil:removable-media`` this will allow you to access /media, so you'd need to mount your drive as /media/data instead of /data
2. move your KVM folder into your home directory as snap can read this.

**Comment by flexiondotorg** [comment]
I can't reproduce this issue. If it is still a problem please provide more information and we can re-open it :slightly_smiling_face:

**Comment by osgyan** [comment]
Hi Martin,
Hope you are doing great. 

Yes the problem exists and looks like a general issue with Snap Packages.
I am on elementary OS at this time, however the behaviour is the same
__________________________________________________
rajat@beasty:~/quickemu$ ./quickemu --vm ubuntu.conf 
Starting ubuntu.conf
 - QEMU:     /snap/bin/qemu-virgil v4.2.0
 - BOOT:     Legacy BIOS
 - Guest:    Linux optimised
 - Disk:     /Data/KVM/elementary.qcow2 (128G)
qemu-img: /Data/KVM/elementary.qcow2: Could not create file: No such file or directory
ERROR! Failed to create /Data/KVM/elementary.qcow2
____________________________________________________
I am referring to the below bug with snapd. This means I can't browse outside my $HOME and my Disk location is on a secondary drive mapped to /Data.
_______________________________________________________________________________________
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1643706

This bug has been changed to Fix released when clearly there is no fix released for it. This is very discouraging for anyone who wants to report a bug. I see multiple people confirming that this issue exists yet nobody  has any answers for us. Not everybody is on a System with Single Disk. I have been a Linux user for 10 years and this is why I hate filing bugs nothing gets done unless you reach out to the likes of you, or the developers directly. 

I am using Flatpak for all my other applications but I love snaps equally but can't use them if they can't see my main Data drive. 
_________________________________________________________________________________________
If I change the path of the Image File to a directory in my $HOME. everything works as expected.
Apologies for my Rant.
Thanks for a great project. I am a regular listener on Ubuntu Podcast and all other shows where you appear from time to time.

Appreciate your time on this one. Keep up the great work.

Happy to provide further information if required. Happy to communicate text or voice or your latest favourite Discord.

:+1:
