### ISSUE TITLE
-spice port=,disable-ticketing: Parameter 'port' expects a number

### ISSUE THREAD

**Issue by AnErrupTion** [wimpysworld/quickemu#39]
Hey!
So I've implemented the way to get an available port in my fork, however, it doesn't seem to work (and the function "get_port" itself hasn't been modified or anything).
When I launch qemu, I have this error :
"-spice port=,disable-ticketing: Parameter 'port' expects a number"
I'm kinda confused because that function "get_port" doesn't actually return anything. I have Elementary OS Hera with latest updates installed, don't see why it doesn't work.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/quickemu/pull/29
