### ISSUE TITLE
Fedora Support

### ISSUE THREAD

**Issue by thedrewster-u51** [wimpysworld/quickemu#47]
In order to use this on fedora, you'll need an extra step in your instructions and a minor tweak in the script. It looks like "snap" isn't installed by default. It's also fair to assume if someone knows what this script does, they will know how to install snaps on Fedora.

Then, the snap binaries are in a different location in Fedora (At least Fedora 32, wasn't able to confirm other versions). Instead of `/snap/bin` they are in `/var/lib/snapd/snap/bin/`.  Therefore, you end up with an error of `"ERROR! qemu-virgil not found. Please install the qemu-virgil snap.`, when in reality, it very much is installed.

So you can do one of two things for Fedora. 

 - As an extra step, symlink `/var/lib/snapd/snap` to `/snap`
OR
- Add a check in the script for Fedora / Redhat, and adjust the path of the snap binaries to `/var/lib/snapd/snap/bin/`

Something like:
```
SNAP_PATH="/snap"
if [ -e "/etc/redhat-release" ] && [ $( grep -i fedora -c /etc/redhat-release ) -gt 0 ]; then
  SNAP_PATH="/var/lib/snapd/snap"
fi
QEMU="${SNAP_PATH}/bin/qemu-virgil"
QEMU_IMG="${SNAP_PATH}/bin/qemu-virgil.qemu-img"
VIRGIL_PATH="${SNAP_PATH}/qemu-virgil/current"
```

**Comment by markvarvel** [comment]
Nice catch and check.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/quickemu/commit/8c642fd3efada6416356f40244c4d5a9c126d0e3

Quickemu now uses the host installed `qemu`.
