### ISSUE TITLE
Network bridge

### ISSUE THREAD

**Issue by Nebucatnetzer** [wimpysworld/quickemu#48]
Is there a way to make the network for the VM bridged?
This would be handy to test for network printers and the likes.

**Comment by flexiondotorg** [comment]
Network bridges require tap/tun interfaces to be configured. While network bridging is a great feature it is out of scope for `quickemu`, which is designed to be a means of taking your VMs with you on USB drive and just work on any Linux without configuration 🙂

**Comment by Nebucatnetzer** [comment]
I was just curios of a way to achieve it in general. 
Wouldn’t be a problem if it wasn’t through quickemu.
