### ISSUE TITLE
Is there a way to install from a Snow leopard 10.6.3 DVD, for Rosetta

### ISSUE THREAD

**Issue by KDGNOR** [wimpysworld/quickemu#49]
Would it be possible to add Snow Leopard ?

While there are many older versions of OSX, Snow Leopard is the last version to run PPC apps with Rosetta.

some way use Tiger 10.4, Leoaprd 10.5, Snow Leopard 10.6, Lion 10.7?

**Comment by daPhipz** [comment]
I don't really know much about macOS VMs, but it may be worth checking out the `sosumi` snap. It bundles everything you need to spin up a Mac VM. Not sure what version of macOS, though...

**Comment by KDGNOR** [comment]
it only support the newest macOS 10.1+.+

**Comment by flexiondotorg** [comment]
`quickemu` doesn't provide any tooling to acquite macOS, that is down to you. All `quickemu` offers is the means to run macOS in a VM. So, sorry, but you request is out of scope for the project 🙂
