### ISSUE TITLE
/usr/share/libdrm/amdgpu.ids: No such file or directory

### ISSUE THREAD

**Issue by ameeno** [wimpysworld/quickemu#50]
Hello, i get this error when running quickemu (using wayland ubuntu 20.10)

laptop is a ryzen 4800u ideapad 15are05, qemu-virgil is edge version.

**Comment by FreaxMATE** [comment]
Same with up-to-date Manjaro  on Thinkpad E14 Gen 2 with AMD Ryzen 5 4500U and Radeon Graphics.

**Comment by antonyshen** [comment]
My PC is a Lenovo M75q Gen 2, it equips with a Ryzen 7 4750GE APU, I encountered the same issue. But I thought this is not an issue of quickemu but the qemu-virgl snap. I saw same issue on PPSSPP, 0ad, ... snaps too. Raised issues with PPSSPP developer, still cannot resolve this one.

**Comment by tuxtergames** [comment]
same issue here with an ryzen 5 + rx5600, maybe this error blocking acceleration of VM, maybe is looking for amdgpu pro, I use mesa drivers here, looking for and answer.....

**Comment by AnErrupTion** [comment]
Do you see `qemu-system-x86_64: ` before the error message or not?

**Comment by FreaxMATE** [comment]
> Do you see `qemu-system-x86_64: ` before the error message or not?

Yap:

```bash
[kunruh@thinkfreax quickemu]$ ./quickemu --vm manjaro_mate.conf 
Starting manjaro_mate.conf
 - QEMU:     /snap/bin/qemu-virgil v4.2.0
 - BOOT:     Legacy BIOS
 - Guest:    Linux optimised
 - Disk:     /home/kunruh/opt/quickemu/manjaro_mate.iso (32G)
             Looks unused, booting from /home/kunruh/opt/quickemu/manjaro-mate-20.2-201212-linux59.iso
 - Boot:     /home/kunruh/opt/quickemu/manjaro-mate-20.2-201212-linux59.iso
 - CPU:      2 Core(s)
 - RAM:      2G
 - Screen:   1664x936
 - Video:    virtio-vga
 - GL:       ON
 - Virgil3D: ON
 - Display:  SDL
 - smbd:     /home/kunruh will be exported to the guest via smb://10.0.2.4/qemu
 - ssh:      22223/tcp is connected. Login via 'ssh user@localhost -p 22223'
qemu-system-x86_64: -drive media=cdrom,index=0,file=/home/kunruh/opt/quickemu/manjaro-mate-20.2-201212-linux59.iso: Could not open '/home/kunruh/opt/quickemu/manjaro-mate-20.2-201212-linux59.iso': Permission denied
[kunruh@thinkfreax quickemu]$ 

```

**Comment by FreaxMATE** [comment]
> Do you see `qemu-system-x86_64: ` before the error message or not?

Yap, it seems to be a general snap bug.

**Comment by omdv** [comment]
Just checking if there is any progress or resolution. Have this issue with Lenovo T14 AMD.

**Comment by subhajit-halder** [comment]
I have the same issue on Pop_os 20.10 host
The (linux mint) vm is booting, but the display is showing black screen, I can `ctrl+alt+t` and type `poweroff` to shutdown the vm.
The same issue occurs when enabling opengl using virt-manager.

Complete terminal output 
``` 
~/Downloads/virtual-machines 
➞  quickemu --vm mint.conf
Starting mint.conf
 - QEMU:     /snap/bin/qemu-virgil v4.2.0
 - BOOT:     Legacy BIOS
 - Guest:    Linux optimised
 - Disk:     /media/subhajit/93d0ce2d-f412-486d-8175-d28f7c54f297/quickemu/mint.qcow2 (20G)
             Looks unused, booting from /home/subhajit/Downloads/virtual-machines/linuxmint-20.1-xfce-64bit.iso
 - Boot:     /home/subhajit/Downloads/virtual-machines/linuxmint-20.1-xfce-64bit.iso
 - CPU:      4 Core(s)
 - RAM:      2G
 - Screen:   1664x936
 - Video:    virtio-vga
 - GL:       ON
 - Virgil3D: ON
 - Display:  SDL
 - smbd:     /home/subhajit will be exported to the guest via smb://10.0.2.4/qemu
 - ssh:      22221/tcp is connected. Login via 'ssh user@localhost -p 22221'
 - PORTS:    Port forwards requested:
              - 8123 => 8123
              - 8888 => 80
/usr/share/libdrm/amdgpu.ids: No such file or directory
gl_version 46 - core profile enabled
GLSL feature level 430    
```

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/quickemu/commit/8c642fd3efada6416356f40244c4d5a9c126d0e3

Quickemu no longer used the `qemu-virgil` snap, but instead uses system installed QEMU.
