### ISSUE TITLE
Feature request: allow booting from raw disk (/dev/sdX)

### ISSUE THREAD

**Issue by N0rbert** [wimpysworld/quickemu#52]
It would be really great if you add an ability to boot the VM from existing physical raw disk. 

Something like `-drive file=${RAW_DISK},format=raw,if=virtio` with `RAW_DISK=/dev/sdX` (and special config-file option) will be very useful.

---

Note: this idea was inspired by this [AskUbuntu Q&A](https://askubuntu.com/q/1314825/66509).

**Comment by flexiondotorg** [comment]
While this is a nifty idea, it is well outside the scope of what `quickemu` is intended for 🙂
