### ISSUE TITLE
Request: Add libvirt to PPA

### ISSUE THREAD

**Issue by lfom** [wimpysworld/quickemu#55]
Hello!

I have found quickemu recently, and I was glad you offer it as a PPA with latest qemu as well. But installing latest qemu breaks libvrt, what by its turn breaks virt-manager and gnome-boxes. Is there any change you can add latest [libvirt](https://libvirt.org/downloads.html) to the PPA as well?

Anyway, thanks for this nice tool, it seems to work better with macOS images (perhaps because of the new qemu version)!

Regards

**Comment by flexiondotorg** [comment]
I'll look into it 👍

**Comment by lfom** [comment]
@flexiondotorg I have installed quickemu on Pop!_OS 21.04, it's based on Ubuntu 21.04 (hirsute).
Thank you again.

**Comment by flexiondotorg** [comment]
libvirt 7.6.0 is now added to the PPA.
