### ISSUE TITLE
quickget: command not found

### ISSUE THREAD

**Issue by valtanetz** [wimpysworld/quickemu#59]
Hello, 

Using Quickemu since 3 months, love it, i was installing it on a new computer and discover the quickemu package, so i try it.

and the new commend quickget 

Reading the documentation,, i was impress look  great and simple, let try it .... but 

quickget: command not found

So i will continue with the old method. The command quickemu is working properly

But i think it's important to inform you, as you are doing a great job

Valtanetz

**Comment by valtanetz** [comment]
I have installed quickemu on Pop!_OS 21.04, it's based on Ubuntu 21.04 (hirsute).

**Comment by flexiondotorg** [comment]
Quickemu 2.1.0 is published in the PPA and it now includes `quickget`.
