### ISSUE TITLE
Change readme instructions to sudo snap refresh --edge qemu-virgil

### ISSUE THREAD

**Issue by hjolli** [wimpysworld/quickemu#6]
Change readme instructions to sudo snap refresh --edge qemu-virgil

The removable-media  plug is not in stable snap yet.

https://github.com/ogra1/qemu-virgil-snap/issues/5#issuecomment-601703741

**Comment by ogra1** [comment]
well, it will soon be in stable i wont change the instructions for this ... since it is a temporary condition :)

**Comment by AnErrupTion** [comment]
Well it's better since you have the latest version (4.2.0) and so you can use the [documentation](https://qemu.weilnetz.de/doc/qemu-doc.html#index-_002dusb) to add more parameters when launching QEMU.
