### ISSUE TITLE
Errors with windows 11

### ISSUE THREAD

**Issue by sgmihai** [wimpysworld/quickemu#64]
quickget windows 11
Getting Windows 11 URL...
.....
[====================================================================================================>] 530,65M  22,3MB/s    in 25s     
Making unattended.iso
/usr/bin/quickget: line 85: windows-11/unattended/autounattend.xml: No such file or directory
mkisofs: No such file or directory. Invalid node - 'windows-11/unattended/'.
Making VM configuration for windows-11...

quickemu --vm windows-11.conf

Still I can start it, but, when starting the install process I get that "Thgis PC does not meet the minimum requirements bla bla" (that tpm thing that win11 needs).

Edit: Same thing happens with the win10 image. I'm thinking it's supposed to install unattended, but for some reason this doesn't work. Not sure if the unattended part is related to win11 tpm issue. I have the necessary dependencies.

Anyone can take a look at the issue?

**Comment by cirrusflyer** [comment]
I'm also having the "this PC doesn't meet the minimum system requirements" message when installing Windows 11.  And the TPM setting is on in the conf file.  I understand it's using swtpm.  Do I need to install that or is it already included?
