### ISSUE TITLE
Running quickemu fails with "fsdev0 failed to open"

### ISSUE THREAD

**Issue by mark2185** [wimpysworld/quickemu#68]
Just following the example, `./quickget ubuntu focal` completes as expected.

But then this fails
```
$> ./quickemu --vm ubuntu-focal.conf
Quickemu 2.2.2 starting ubuntu-focal.conf
 - QEMU:     /usr/bin/qemu-system-x86_64 v6.1.0
 - BOOT:     Legacy BIOS (linux) - EFI requested but no EFI firmware found.
 - CPU:      1 Socket(s), 4 Core(s), 2 Thread(s), 2G RAM
 - Disk:     ubuntu-focal/disk.qcow2 (16G)
             Looks unused, booting from ubuntu-focal/ubuntu-20.04.3-desktop-amd64.iso
 - Boot ISO: ubuntu-focal/ubuntu-20.04.3-desktop-amd64.iso
 - Screen:   1664x936
 - Display:  SDL, virtio-vga, GL (on), VirGL (on)
 - ssh:      On host:  ssh user@localhost -p 22226
 - SPICE:    On host:  spicy --title "ubuntu-focal" --port 5937 --spice-shared-dir 
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600  ~/Public
 - Process:  On guest: killall ubuntu-focal	(if a forced kill is required)
qemu-system-x86_64: -device virtio-9p-pci,fsdev=fsdev0,mount_tag=: cannot initialize fsdev 'fsdev0': failed to open '': No such file or directory
```

This is on `archlinux`, latest `master`.

**Comment by arp242** [comment]
This is related to #65; the arguments it adds is:

          args+=(-fsdev local,id=fsdev0,path="${PUBLIC}",security_model=mapped-xattr
             -device virtio-9p-pci,fsdev=fsdev0,mount_tag="${PUBLIC_TAG}")

However, if you don't have `xdg-user-dirs` or if the command returns your home directory, then `$PUBLIC` will be an empty string, and hence the error `failed to open '': No such file or directory`.

I think, ehm, that the default should probably be either `$HOME` or the current directory? Or maybe just not bother setting up the FS sharing at all?

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/quickemu/commit/fd52be1dfb059049efb93ec8dd9a672f68ab71b3
