### ISSUE TITLE
Windows 10 doesn't detect the qcow2 hdd

### ISSUE THREAD

**Issue by AnErrupTion** [wimpysworld/quickemu#7]
For me, Windows 10 doesn't detect the qcow2 hdd.
No errors, it just can't detect it. I can't add anything more, but it's really strange.

Also, Ubuntu Budgie didn't (or didn't seem to) detect the qcow2 hdd too, since it showed 0 bytes in the HDD. But Ubuntu 20.04 did and Xubuntu did detect the qcow2 hdd. I don't know what's going on.

**Comment by SneWs** [comment]
For Windows 10 you need to have drivers for the qcow2 scsi interface AFAIR and point to the driver disk during installation. See https://www.linux-kvm.org/page/WindowsGuestDrivers/Download_Drivers 

However, I'm a bit puzzled over where to get modern up 2 date drivers for Win10 for example. Perhaps @flexiondotorg or someone more knowledgable might be able to fill in that gap?

**Comment by AnErrupTion** [comment]
But the problem is that you can't change the ISO on the VM in real-time.

**Comment by SneWs** [comment]
> VM

Well, you just need to attach it as a separate drive. `-drive file=my_second.iso,index=0,media=cdrom`

**Comment by AnErrupTion** [comment]
Thanks, it worked! But @flexiondotorg should add this mention in the read me file.
