### ISSUE TITLE
Add ChunkList checker for macOS downloads

### ISSUE THREAD

**Issue by jspraul** [wimpysworld/quickemu#70]
This project is amazing!

Please consider implementing verification of all downloaded content in some manner. It would be awesome if this could be signed (PGP?) vs. checksummed (SHA256) as is already done for the Ubuntu images, though even a checksum is appreciated.

**Comment by goldstar611** [comment]
> From a security perspective, these checksum files are only of value when trying to verify that a file from another source is the same file.

I think you may have missed the OP's point which was to add in GPG verification. You would be correct that the checksum file alone is not useful from a security perspective which is why Canonical (and many others) publishes detached GPG signatures for their downloads.[1]

[1] https://ubuntu.com/tutorials/how-to-verify-ubuntu#3-download-checksums-and-signatures

**Comment by jspraul** [comment]
> What mechanisms exist to do that for macOS and Windows images?

For Windows images, the final [DOWNLOAD_INFO](https://github.com/wimpysworld/quickemu/blob/061c454a8251a030775af08c7e71713d986f4570/quickget#L520) already contains a SHA1 hash that could be verified. ([Example](https://tb.rg-adguard.net/dl.php?fileName=39774&lang=en)) I'm not aware of any cryptographic signature verification of Windows images available from Microsoft, but there is [another public source](https://www.heidoc.net/php/myvsdump.php) for SHA1 hashes that could be used as a second opinion.

Verification of macOS images should probably be an option in the [macrecovery.py](https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/macrecovery/macrecovery.py) script used. It downloads an associated .chunklist file but does not use it to verify the download (checksum) nor verify the .chunklist itself (cryptographic signature).

I was able to completely verify a downloaded macOS image using [chunckchecker from a gist](https://gist.github.com/MCJack123/943eaca762730ca4b7ae460b731b68e7) and the [Apple-Chunklist-Verification-Creation-Toolkit](https://github.com/sadponyguerillaboy/Apple-Chunklist-Verification-Creation-Toolkit), which includes the public key dumped from Apple EFI ROM:

```
curl -o chunkcheck.zip https://codeload.github.com/gist/943eaca762730ca4b7ae460b731b68e7/zip/b4509719b3378ae96b48d348eef067ba5a42323a
unzip -j chunkcheck.zip -d chunkcheck
cd chunkcheck
gcc chunkcheck.c sha256.c -o chunkcheck
./chunkcheck check ../RecoveryImage.chunklist ../RecoveryImage.dmg -v

cd ..
git clone https://github.com/sadponyguerillaboy/Apple-Chunklist-Verification-Creation-Toolkit.git
cd Apple-Chunklist-Verification-Creation-Toolkit/
pip3 install pycryptodome numpy
python3 verify.py ../RecoveryImage.chunklist efi_keys/01.bin
```

**Comment by flexiondotorg** [comment]
Of the proposed options for checking the macOS chunklist, I much prefer `chunkcheck`.
