### ISSUE TITLE
Proxmox workflow?

### ISSUE THREAD

**Issue by lukegalea** [wimpysworld/quickemu#73]
Hey! This project looks great! 

I was wondering if anyone has a good workflow to use quickemu on proxmox? 

Thanks in advance!

**Comment by flexiondotorg** [comment]
Quickemu is not intended to integrate with Proxmox, nor libvirtd. Sorry.

**Comment by arty-hlr** [comment]
Proxmox uses KVM, like qemu does. I am not sure why you mentioned libvirtd or why it couldn't work with proxmox? That was also my first thought when I found this repo, that would be great for proxmox.
