### ISSUE TITLE
OVMF file stored in different location

### ISSUE THREAD

**Issue by danielfomin96** [wimpysworld/quickemu#74]
Looking at the script, the OVMF file should be located at `/usr/share/OVMF/OVMF_CODE_4M.fd` but this file does not exist on my Arch Linux OS. Instead I have two directories: 
```
$ ls /usr/share/OVMF/
ia32  x64
```
where `x64` includes the following files:
```
$ ls /usr/share/OVMF/x64
OVMF_CODE.fd  OVMF_CODE.secboot.fd  OVMF.fd  OVMF_VARS.fd
```
Would it be possible to make the quickemu script more flexible to accommodate such setups (Which I did not do manually). Or do I understand something incorrectly and I just have to install another package?

**Comment by wioo** [comment]
I think ovmf location should be configurable in vm conf file.

**Comment by wioo** [comment]
On archlinux you need debian's ovmf package with OVMF_CODE_4M.fd file.
It doesnt work with arch's OVMF_CODE.fd.

**Comment by danielfomin96** [comment]
I searched for a package containing „ovmf“ but did not find anything. Do you maybe have the package name on hand which has to be installed?

**Comment by danielfomin96** [comment]
I tried it with OVMF_CODE_4M.fd from the debian package but I still get the following  error:
![Imgur](https://i.imgur.com/KkuKYEi.png)

**Comment by danielfomin96** [comment]
@monetaryabyss Thank you!!! I am now getting to the installation part

**Comment by danielfomin96** [comment]
@Delvien, your approach works but it is probably better to move the extracted files to /usr/share/OVMF instead of /usr/share/OVMF/x64, without renaming them. On my arch system there were no .fd files in this directory which means that no file would need to be overwritten or backed up. Additionally this directory is searched for by quickemu. So I would propose to change your instructions to the following:

    1. download the ovmf package https://packages.debian.org/sid/all/ovmf/download
    2. Extract it with: "ar x ovmf_2021.08-2_all.deb"
    3. Locate the OVMF_CODE_4M.fd file in /where_you_extracted_deb/usr/share/OVMF/
    (3.1 Ensure that no file would be overwritten in /usr/share/OVMF) 
    4. mv this to /usr/share/OVMF
    5. start your VM and install.
