### ISSUE TITLE
Allocate too little memory for Windows 11

### ISSUE THREAD

**Issue by domingo13** [wimpysworld/quickemu#78]
The default Windows 11 configuration only allocate 2G of memory which isn't enough.

Add:
ram="4" 
in windows-11.conf to meet the bare minimum.

**Comment by flexiondotorg** [comment]
@cirrusflyer HOw much RAM do you have on your host computer?

**Comment by cirrusflyer** [comment]
> @cirrusflyer How much RAM do you have on your host computer?

32 GB

**Comment by mirzaindra** [comment]
how do you update size of RAM, processor, & disk? where is the configuration file is located?
