### ISSUE TITLE
Why is the 9p mount code in the SPICE block?

### ISSUE THREAD

**Issue by navycatt** [wimpysworld/quickemu#85]
Why is the 9p mount code in the SPICE block?
https://github.com/wimpysworld/quickemu/blob/018fb1c454545795b271206a11ef6445178f52b0/quickemu#L639-L652
This is a standalone feature.
Sharing folder in SPICE works over WebDAV.

https://gitlab.freedesktop.org/spice/spice-gtk/-/blob/master/src/spice-session.c#L1496-L1497
```
     * Phodav server that is internally used by #SpiceSession to make
     * #SpiceSession:shared-dir available to the host.
```
This issue has been resolved in PR: https://github.com/wimpysworld/quickemu/pull/87.

**Comment by flexiondotorg** [comment]
Good catch! Thanks :+1:
