### ISSUE TITLE
Windows 10 & 11 not booting (in some cases) unless ignore_msrs is enabled

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/quickemu#88]
( btw Thanks for another awesome project Martin! )

Some sort of curious windows-hates-me-back going on.  Probably hardware-specific/my fault but whilst windows 10 installs and runs fine under KVM using Virtual Machine Manager, using the latest quickemu gets into a boot loop with a Black SOD wingeing about System Thread Exception (and the same but Blue with Win10)
![win11bsod](https://user-images.githubusercontent.com/8797027/136695772-03f90acf-d70f-4000-9672-fc153fd00696.png)

Quickemu 2.2.4 starting windows-11.conf
 - QEMU:     /usr/bin/qemu-system-x86_64 v6.0.0
 - BOOT:     EFI (windows)
 - CPU:      1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - Disk:     windows-11/disk.qcow2 (64G)
             Looks unused, booting from windows-11/Win11_EnglishInternational_x64.iso
 - Boot ISO: windows-11/Win11_EnglishInternational_x64.iso
 - CD-ROM:   windows-11/virtio-win.iso
 - TPM:      windows-11/windows-11.swtpm-sock (608541)
 - Screen:   1664x936
 - Display:  SDL, qxl-vga, GL (on), VirGL (off)
-------------- 
OS: Ubuntu MATE 21.04 x86_64 
Kernel: 5.11.0-37-lowlatency 
Uptime: 1 day, 22 mins 
Packages: 5630 (dpkg), 17 (flatpak), 83 (snap) 
Shell: bash 5.1.4 
Resolution: 1920x1200 
DE: MATE 1.24.2 
WM: Metacity (Marco) 
Theme: Ambiant-MATE-Dark [GTK2/3] 
Icons: Yaru-MATE-light [GTK2/3] 
Terminal: mate-terminal 
Terminal Font: Ubuntu Mono 13 
CPU: AMD Ryzen Threadripper 1920X (24) @ 3.500GHz 
GPU: AMD ATI Radeon RX 550 640SP / RX 560/560X 
Memory: 23075MiB / 31958MiB

**Comment by flexiondotorg** [comment]
Try this before starting the VM.

echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

**Comment by mainmachine** [comment]
> Try this before starting the VM.
> 
> ```
> echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs
> ```

This works for me on Ubuntu 20.04 with a Windows 10 VM. Thanks Wimpy!

**Comment by philclifford** [comment]
Works for me also for Win 10 (now on  
~~~
OS: Ubuntu MATE 21.10 x86_64 
Kernel: 5.13.0-19-generic 
~~~
when that's finished updating I expect Win11 will also be fine...

**Comment by kriscamilleri** [comment]
> Works for me also for Win 10 (now on
> 
> ```
> OS: Ubuntu MATE 21.10 x86_64 
> Kernel: 5.13.0-19-generic 
> ```
> 
> When that's finished updating I expect Win11 will also be fine... Yup, all good too (well it's on reboot 3 or 4 and updating so "good" is kinda relative but ...
> 
> Hmmm ... after checking for updates Windows 11 now forces login to Microsoft ("your work or school") and the only other alternatives are login with a key or join a domain (which then fails) ... (may need to re-open issue #115 to which I've added a video)
> 
> I think maybe there has been a threshold passed with the activation key or ...
> 
> Whatever - _this_ issue seems to have a reasonable workaround.
> 
> Thanks Martin!

For setting up Windows 11, I manually disabled networking on the host, and the guest Windows 11 OS prompted me to create a local account. All seems to work fine now.
