### ISSUE TITLE
Add support for macOS 10.12 (Sierra)

### ISSUE THREAD

**Issue by jrmuizel** [wimpysworld/quickemu#91]
An install image is available here: http://updates-http.cdn-apple.com/2019/cert/061-39476-20191023-48f365f4-0015-4c41-9f44-39d3d2aca067/InstallOS.dmg

**Comment by flexiondotorg** [comment]
Sorry, I wasn't able to get Sierra working with Clover or OpenCore. Given that Sierra is also 2 years EOL, I don't see that value in trying to make it work.
