### ISSUE TITLE
XML config file for libvirt?

### ISSUE THREAD

**Issue by phmarek** [wimpysworld/quickemu#92]
Hi,

is there a way to get an XML file for use with `libvirt`?
And would you please dump example command lines for a few common configurations into a text file in git?

I've got an existing VM and would like to fetch some improvements without reinstalling.

Thank you!

**Comment by flexiondotorg** [comment]
Sorry, `quickemu` doesn't create libvirt XML. It is not is goal I have for the project. However, quickemu does drop a non-executable shell script of the last run use the invoke you VM in the virtual machine's directory, which might help you 🙂

  * https://github.com/wimpysworld/quickemu/blob/master/quickemu#L780
